apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
  labels:
    app: testapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp1
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
      - name: testapp1
        image: ghcr.io/yatri-motorcycles/testapp1:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 204m
            memory: 512Mi
          requests:
            cpu: 204m
            memory: 512Mi
        envFrom:
        - secretRef:
            name: testapp1-secrets
        
        env:
        
        
        
        
        
        
        
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        
        
        
         