apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
  namespace: utils
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
      - name: testapp1
        image: 147728078333.dkr.ecr.ap-south-1.amazonaws.com/testapp1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: testapp1-secret
        env: - name: DOMAIN_NAME
  value: mydomain
- name: REDIS_HOST
  value: redis-master.default.svc.cluster.local
- name: REDIS_PORT
  value: '6379'
- name: claude
  value: qwertyqwerty
- name: debug_level
  value: 'false'

        resources:
          requests:
            cpu: 203m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 