apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-domain-1
  labels:
    app: my-domain-1
  namespace: utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-domain-1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: my-domain-1
    spec:
      containers:
      - name: my-domain-1
        image: 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        envFrom:
        - secretRef:
            name: my-domain-1-secrets
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 