apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp1
  namespace: utils
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
      - env:
        - name: DOMAIN_NAME
          value: example.com
        - name: CLICKHOUSE_HOST
          value: 10.6.155.14
        - name: CLICKHOUSE_PORT
          value: '9000'
        - name: CLICKHOUSE_DATABASE
          value: atlas_driver_offer_bpp
        - name: claude
          value: qwertyqwerty
        - name: DEBUG
          value: 'false'
        envFrom:
        - secretRef:
            name: testapp1-secret
        image: 147728078333.dkr.ecr.ap-south-1.amazonaws.com/testapp1:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        name: testapp1
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 201m
            memory: 512Mi
