apiVersion: v1
kind: Secret
metadata:
  name: testapp1-secrets
type: Opaque
data:
  
  claude: cXdlcnR5cXdlcnR5
  
  debug_level: ZmFsc2U=
  
  
  
  
  
  
  
  
  
  REDIS_PASSWORD: cmVkaXMxMjM=
  
  
  
   