name: Build and Deploy
'on':
  push:
    branches:
    - main
env:
  API_BASE_URL: ${{ secrets.API_BASE_URL }}
  APP_NAME: testapp1
  NAMESPACE: utils
  AWS_REGION: ap-south-1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and push Docker image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: '|'
    - name: Check if deployment exists via API
      id: check-deployment
      run: '|'
    - name: Call API to patch deployment
      if: steps.check-deployment.outputs.exists == 'true'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: '|'
    - name: Apply K8s files via API if deployment doesn't exist
      if: steps.check-deployment.outputs.exists == 'false'
      run: '|'
