jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ap-south-1
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - id: login-ecr
      name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and push Docker image
      run: 'docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name
        }}:${{ github.sha }} .

        docker push ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name
        }}:${{ github.sha }}'
    - name: Update deployment
      run: kubectl patch deployment ${{ github.event.repository.name }} -n utils --patch
        '{"spec":{"template":{"spec":{"containers":[{"name":"${{ github.event.repository.name
        }}","image":"${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name
        }}:${{ github.sha }}"}]}}}}'
name: Build and Deploy
'on':
  push:
    branches:
    - main
